export const DATE_FORMAT_REG = 'DD/MM/YYYY';
export const dayAndTimeHourFormat = 'DD/MM/YYYY HH:mm';
export const dateInputFormat = 'DD/MM/YYYY';
export const dateToTextFormat = 'dddd, MMMM, Do, YYYY';
export const weekdayFormat = 'dddd';
export const dayFormat = 'dddd Do';
export const dateFormatCalendar = 'D';
export const timeFormat = 'HH:mm';
export const appointmentTimeFormat = 'MMMM DD, YYYY - dddd';
