export const navigation = {
  home: '/',
  login: '/login',
  register: '/register',
  forgetPassword: '/forget-assword',
  dashboard: '/dashboard',
  appointments: '/appointments',
  profile: '/profile',
  resetPassword: '/reset-password/:token',
  patientList: '/patient-list',
  help: '/help',
  exit: '/logout',
  resendConfirmation: '/re-confirm-account',
  updatePassword: '/update-password',
};
